title: "Gabriel Hubermann"
tagline: "Software, ideas, and experiments"
description: "Personal tech blog by Gabriel Hubermann"
url: "https://hubermann.github.io"
baseurl: "" # keep it blank for user.github.io

author:
  name: Gabriel Hubermann
  email: gabriel@example.com

avatar: "/assets/images/avatar.jpg"

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

social:
  github: hubermann
  linkedin: https://www.linkedin.com/in/gabriel-hubermann-6786915/
  email: hubermann@gmail.com
